services:
  postgres:
    image: postgres:17
    container_name: bananacar-notification-svc-postgres-db
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bananacar_notification_svc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bananacar-network

  spring-app:
    image: bananacar-notification-svc:latest
    container_name: bananacar-notification-svc-app
    depends_on:
      - postgres
      - selenium
    networks:
      - bananacar-network

  selenium:
    image: selenium/standalone-firefox
    container_name: selenium-firefox
    environment:
      SE_ENABLE_TRACING: false
    ports:
      - "4444:4444"
    shm_size: 2g
    networks:
      - bananacar-network

volumes:
  postgres_data:

networks:
  bananacar-network:
