version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: bananacar-notification-svc-postgres-db
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bananacar_notification_svc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
