/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.bananacar_notification_svc.db.jooq;


import lt.liutikas.bananacar_notification_svc.db.jooq.tables.Ride;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_RIDE_BANANACAR_RIDE_ID = Internal.createIndex(DSL.name("idx_ride_bananacar_ride_id"), Ride.RIDE, new OrderField[] { Ride.RIDE.BANANACAR_RIDE_ID }, false);
}
