/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.bananacar_notification_svc.db.jooq;


import lt.liutikas.bananacar_notification_svc.db.jooq.tables.Ride;
import lt.liutikas.bananacar_notification_svc.db.jooq.tables.RideSubscription;
import lt.liutikas.bananacar_notification_svc.db.jooq.tables.records.JooqRideRecord;
import lt.liutikas.bananacar_notification_svc.db.jooq.tables.records.JooqRideSubscriptionRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JooqRideRecord> RIDE_PKEY = Internal.createUniqueKey(Ride.RIDE, DSL.name("ride_pkey"), new TableField[] { Ride.RIDE.ID }, true);
    public static final UniqueKey<JooqRideSubscriptionRecord> RIDE_SUBSCRIPTION_PKEY = Internal.createUniqueKey(RideSubscription.RIDE_SUBSCRIPTION, DSL.name("ride_subscription_pkey"), new TableField[] { RideSubscription.RIDE_SUBSCRIPTION.ID }, true);
}
