/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.bananacar_notification_svc.db.jooq;


import java.util.Arrays;
import java.util.List;

import lt.liutikas.bananacar_notification_svc.db.jooq.tables.Ride;
import lt.liutikas.bananacar_notification_svc.db.jooq.tables.RideSubscription;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ride</code>.
     */
    public final Ride RIDE = Ride.RIDE;

    /**
     * The table <code>public.ride_subscription</code>.
     */
    public final RideSubscription RIDE_SUBSCRIPTION = RideSubscription.RIDE_SUBSCRIPTION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Ride.RIDE,
            RideSubscription.RIDE_SUBSCRIPTION
        );
    }
}
