/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.bananacar_notification_svc.db.jooq.tables;


import java.time.LocalDateTime;

import lt.liutikas.bananacar_notification_svc.db.jooq.Keys;
import lt.liutikas.bananacar_notification_svc.db.jooq.Public;
import lt.liutikas.bananacar_notification_svc.db.jooq.tables.records.JooqRideSubscriptionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RideSubscription extends TableImpl<JooqRideSubscriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ride_subscription</code>
     */
    public static final RideSubscription RIDE_SUBSCRIPTION = new RideSubscription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqRideSubscriptionRecord> getRecordType() {
        return JooqRideSubscriptionRecord.class;
    }

    /**
     * The column <code>public.ride_subscription.id</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ride_subscription.origin_city</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, String> ORIGIN_CITY = createField(DSL.name("origin_city"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.ride_subscription.destination_city</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, String> DESTINATION_CITY = createField(DSL.name("destination_city"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.ride_subscription.departs_on_earliest</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, LocalDateTime> DEPARTS_ON_EARLIEST = createField(DSL.name("departs_on_earliest"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>public.ride_subscription.departs_on_latest</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, LocalDateTime> DEPARTS_ON_LATEST = createField(DSL.name("departs_on_latest"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>public.ride_subscription.created_on</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>public.ride_subscription.updated_on</code>.
     */
    public final TableField<JooqRideSubscriptionRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    private RideSubscription(Name alias, Table<JooqRideSubscriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private RideSubscription(Name alias, Table<JooqRideSubscriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ride_subscription</code> table reference
     */
    public RideSubscription(String alias) {
        this(DSL.name(alias), RIDE_SUBSCRIPTION);
    }

    /**
     * Create an aliased <code>public.ride_subscription</code> table reference
     */
    public RideSubscription(Name alias) {
        this(alias, RIDE_SUBSCRIPTION);
    }

    /**
     * Create a <code>public.ride_subscription</code> table reference
     */
    public RideSubscription() {
        this(DSL.name("ride_subscription"), null);
    }

    public <O extends Record> RideSubscription(Table<O> child, ForeignKey<O, JooqRideSubscriptionRecord> key) {
        super(child, key, RIDE_SUBSCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<JooqRideSubscriptionRecord> getPrimaryKey() {
        return Keys.RIDE_SUBSCRIPTION_PKEY;
    }

    @Override
    public RideSubscription as(String alias) {
        return new RideSubscription(DSL.name(alias), this);
    }

    @Override
    public RideSubscription as(Name alias) {
        return new RideSubscription(alias, this);
    }

    @Override
    public RideSubscription as(Table<?> alias) {
        return new RideSubscription(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RideSubscription rename(String name) {
        return new RideSubscription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RideSubscription rename(Name name) {
        return new RideSubscription(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RideSubscription rename(Table<?> name) {
        return new RideSubscription(name.getQualifiedName(), null);
    }
}
