/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.bananacar_notification_svc.db.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRideSubscription implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID subscriptionId;
    private String originCity;
    private String destinationCity;
    private LocalDateTime departsOnEarliest;
    private LocalDateTime departsOnLatest;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public JooqRideSubscription() {}

    public JooqRideSubscription(JooqRideSubscription value) {
        this.subscriptionId = value.subscriptionId;
        this.originCity = value.originCity;
        this.destinationCity = value.destinationCity;
        this.departsOnEarliest = value.departsOnEarliest;
        this.departsOnLatest = value.departsOnLatest;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public JooqRideSubscription(
        UUID subscriptionId,
        String originCity,
        String destinationCity,
        LocalDateTime departsOnEarliest,
        LocalDateTime departsOnLatest,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.subscriptionId = subscriptionId;
        this.originCity = originCity;
        this.destinationCity = destinationCity;
        this.departsOnEarliest = departsOnEarliest;
        this.departsOnLatest = departsOnLatest;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>public.ride_subscription.subscription_id</code>.
     */
    public UUID getSubscriptionId() {
        return this.subscriptionId;
    }

    /**
     * Setter for <code>public.ride_subscription.subscription_id</code>.
     */
    public JooqRideSubscription setSubscriptionId(UUID subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }

    /**
     * Getter for <code>public.ride_subscription.origin_city</code>.
     */
    public String getOriginCity() {
        return this.originCity;
    }

    /**
     * Setter for <code>public.ride_subscription.origin_city</code>.
     */
    public JooqRideSubscription setOriginCity(String originCity) {
        this.originCity = originCity;
        return this;
    }

    /**
     * Getter for <code>public.ride_subscription.destination_city</code>.
     */
    public String getDestinationCity() {
        return this.destinationCity;
    }

    /**
     * Setter for <code>public.ride_subscription.destination_city</code>.
     */
    public JooqRideSubscription setDestinationCity(String destinationCity) {
        this.destinationCity = destinationCity;
        return this;
    }

    /**
     * Getter for <code>public.ride_subscription.departs_on_earliest</code>.
     */
    public LocalDateTime getDepartsOnEarliest() {
        return this.departsOnEarliest;
    }

    /**
     * Setter for <code>public.ride_subscription.departs_on_earliest</code>.
     */
    public JooqRideSubscription setDepartsOnEarliest(LocalDateTime departsOnEarliest) {
        this.departsOnEarliest = departsOnEarliest;
        return this;
    }

    /**
     * Getter for <code>public.ride_subscription.departs_on_latest</code>.
     */
    public LocalDateTime getDepartsOnLatest() {
        return this.departsOnLatest;
    }

    /**
     * Setter for <code>public.ride_subscription.departs_on_latest</code>.
     */
    public JooqRideSubscription setDepartsOnLatest(LocalDateTime departsOnLatest) {
        this.departsOnLatest = departsOnLatest;
        return this;
    }

    /**
     * Getter for <code>public.ride_subscription.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>public.ride_subscription.created_on</code>.
     */
    public JooqRideSubscription setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>public.ride_subscription.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>public.ride_subscription.updated_on</code>.
     */
    public JooqRideSubscription setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqRideSubscription other = (JooqRideSubscription) obj;
        if (this.subscriptionId == null) {
            if (other.subscriptionId != null)
                return false;
        }
        else if (!this.subscriptionId.equals(other.subscriptionId))
            return false;
        if (this.originCity == null) {
            if (other.originCity != null)
                return false;
        }
        else if (!this.originCity.equals(other.originCity))
            return false;
        if (this.destinationCity == null) {
            if (other.destinationCity != null)
                return false;
        }
        else if (!this.destinationCity.equals(other.destinationCity))
            return false;
        if (this.departsOnEarliest == null) {
            if (other.departsOnEarliest != null)
                return false;
        }
        else if (!this.departsOnEarliest.equals(other.departsOnEarliest))
            return false;
        if (this.departsOnLatest == null) {
            if (other.departsOnLatest != null)
                return false;
        }
        else if (!this.departsOnLatest.equals(other.departsOnLatest))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        if (this.updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!this.updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.subscriptionId == null) ? 0 : this.subscriptionId.hashCode());
        result = prime * result + ((this.originCity == null) ? 0 : this.originCity.hashCode());
        result = prime * result + ((this.destinationCity == null) ? 0 : this.destinationCity.hashCode());
        result = prime * result + ((this.departsOnEarliest == null) ? 0 : this.departsOnEarliest.hashCode());
        result = prime * result + ((this.departsOnLatest == null) ? 0 : this.departsOnLatest.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqRideSubscription (");

        sb.append(subscriptionId);
        sb.append(", ").append(originCity);
        sb.append(", ").append(destinationCity);
        sb.append(", ").append(departsOnEarliest);
        sb.append(", ").append(departsOnLatest);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
